### ISSUE TITLE
按照tryme的方法，执行训练报错了，不知道什么问题了？是版本不对吗？

### ISSUE THREAD

**Issue by alwin1988** [alibaba-damo-academy/kws-training-suite#12]
2024-08-21 10:44:07,060 - modelscope - INFO - KWSDataset init SoundConnect...
Traceback (most recent call last):
  File "/root/metahuman/kws-training-suite/pipeline.py", line 280, in <module>
    main(conf, args.remote_dataset, args.base_only)
  File "/root/metahuman/kws-training-suite/pipeline.py", line 55, in main
    train(cfg, first_train_dir, max_epochs=first_epoch_num)
  File "/root/metahuman/kws-training-suite/pipeline.py", line 201, in train
    trainer.train()
  File "/root/miniconda3/envs/metahuman-train/lib/python3.10/site-packages/modelscope/trainers/audio/kws_farfield_trainer.py", line 171, in train
    self.gen_val()
  File "/root/miniconda3/envs/metahuman-train/lib/python3.10/site-packages/modelscope/trainers/audio/kws_farfield_trainer.py", line 266, in gen_val
    dataset, dataloader = self.create_dataloader(self.conf_files[2],
  File "/root/miniconda3/envs/metahuman-train/lib/python3.10/site-packages/modelscope/trainers/audio/kws_farfield_trainer.py", line 285, in create_dataloader
    dataset = KWSDataset(base_path, finetune_path, self._threads,
  File "/root/miniconda3/envs/metahuman-train/lib/python3.10/site-packages/modelscope/msdatasets/dataset_cls/custom_datasets/audio/kws_farfield_dataset.py", line 49, in __init__
    self.setup_sims(conf_basetrain, conf_finetune, numworkers,
  File "/root/miniconda3/envs/metahuman-train/lib/python3.10/site-packages/modelscope/msdatasets/dataset_cls/custom_datasets/audio/kws_farfield_dataset.py", line 75, in setup_sims
    fs = py_sound_connect.FeatSimuKWS(self.base_conf.params)
RuntimeError: Caught an unknown exception!

![微信截图_20240821105142](https://github.com/user-attachments/assets/d27d142b-5afc-41e7-b8f2-4edf7a66225c)

**Comment by alwin1988** [comment]
解决了，有需要安装的组件没装

**Comment by tsubasa617** [comment]
> 解决了，有需要安装的组件没装

你好，请问是什么没装？我也报这个错误了，但是是按照说明把依赖都装上了的

**Comment by yousirui1** [comment]
> 解决了，有需要安装的组件没装

能请问一下是什么组件没安装吗？我也遇到同样的问题，但是我都是按照README.md 按照的
