### ISSUE TITLE
按照 Readme 复现训练出错

### ISSUE THREAD

**Issue by YuchengWang** [alibaba-damo-academy/kws-training-suite#6]
您好，我按照 readme 的教程，在配置和运行这一步时，出现以下错误。没有更改配置文件中的任何内容。

麻烦看一下，谢谢

运行环境是直接拉取的GPU docker，本地有GPU的支持了。

```
ycwang@0bc2ef9ef5fb:~/kws-training-suite$ python pipeline.py config.yml --remote_dataset /data/open_dataset
2023-05-25 09:53:47,055 - modelscope - INFO - PyTorch version 1.11.0+cu113 Found.
2023-05-25 09:53:47,057 - modelscope - INFO - Loading ast index from /home/ycwang/.cache/modelscope/ast_indexer
2023-05-25 09:53:47,077 - modelscope - INFO - Loading done! Current index file version is 1.1.0, with md5 3bbeffe7ab88ccc8c561536fa68ba6c2
2023-05-25 09:53:47,856 - modelscope - INFO - Loading config from config.yml
2023-05-25 09:53:47,860 - modelscope - INFO - Local work dir: /mnt/data/data/ckpt_0923
Traceback (most recent call last):
  File "pipeline.py", line 280, in <module>
    main(conf, args.remote_dataset, args.base_only)
  File "pipeline.py", line 42, in main
    check_conf(cfg, download_dir)
  File "/home/ycwang/kws-training-suite/evaluate/batch_roc.py", line 150, in check_conf
    annos = loadAnnot(cfg['test_pos_anno_dir'])
  File "/home/ycwang/kws-training-suite/evaluate/util/KWSEval.py", line 50, in loadAnnot
    for scene in os.listdir(baseannot):
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data/data/himiya.dev/annotation_pos_4mic'
```

**Comment by YuchengWang** [comment]
另外，  readme中的一句话，  各配置项和说明，参见《KWS训练套件配置说明》。  这个配置说明也没有找到

**Comment by YuchengWang** [comment]
非常感谢
